# Generated by Django 2.0.4 on 2018-04-14 19:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Ідентифікатор [ID]')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Марка авто')),
                ('description', models.TextField(blank=True, default='', max_length=1500, verbose_name='Опис')),
                ('city', models.CharField(default='Чернівці', max_length=100, verbose_name='Місто')),
                ('color', models.CharField(default='Чорний', max_length=100, verbose_name='Колір')),
                ('owner_phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Телефон власника')),
                ('fuel_costs', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Витрати пального')),
                ('price', models.BigIntegerField(default=0, verbose_name='Ціна')),
                ('mileage', models.BigIntegerField(default=0, verbose_name='Пробіг')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=8, verbose_name="Об'єи")),
                ('drive_type', models.CharField(choices=[('full', 'Повний'), ('front', 'Передній'), ('back', 'Задній')], default='full', max_length=20, verbose_name='Тип приводу')),
                ('fuel', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ'), ('gas_petrol', 'Газ/Бензин'), ('hybrid', 'Гібрид'), ('electric', 'Електро'), ('other', 'Інше')], default='petrol', max_length=20, verbose_name='Паливо')),
                ('transmission', models.CharField(choices=[('manual', 'Ручна/Механіка'), ('auto', 'Автомат'), ('tiptronic', 'Типтронік'), ('adaptive', 'Адаптивна'), ('variator', 'Варіатор')], default='manual', max_length=20, verbose_name='Коробка передач')),
                ('transport_type', models.CharField(choices=[('car', 'Легкові'), ('moto', 'Мото'), ('special', 'Спецтехніка'), ('truck', 'Вантажівки'), ('trailer', 'Причепи'), ('bus', 'Автобуси'), ('motorhome', 'Автобудинки'), ('water', 'Водний'), ('air', 'Повітряний')], default='car', max_length=20, verbose_name='Тип транспорту')),
                ('abs', models.BooleanField(default=False, verbose_name='ABS')),
                ('airbag', models.BooleanField(default=True, verbose_name='Подушка безпеки')),
                ('alarms', models.BooleanField(default=False, verbose_name='Сигналізація')),
                ('central_lock', models.BooleanField(default=False, verbose_name='Центральний замок')),
                ('image', models.ImageField(default='', upload_to='car_images', verbose_name='Зображення')),
            ],
        ),
    ]
